version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s - %(method)s - %(url)s - %(status)s - %(duration)s - %(client)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG

  file:
    class: logging.FileHandler
    formatter: simple
    level: DEBUG
    encoding: utf-8

loggers:
  uvicorn.access:
    handlers: [console, file]
    level: INFO
    propagate: no
  fastapi:
    handlers: [console, file]
    level: INFO
    propagate: no
  app:
    handlers: [console, file]
    level: DEBUG
    propagate: yes

root:
  handlers: [console, file]
  level: INFO
